# Kubernetes gateway API required for non http/https ingress
# Versions above v0.7.1 are incompatible with traefik's gateway integration (v1alpha2 only)
# Also compatible with cert-manager
resources:
  - https://github.com/kubernetes-sigs/gateway-api/releases/download/v0.7.1/experimental-install.yaml
