namespace: home-assistant

images:
  - name: homeassistant/aarch64-addon-matter-server
    newTag: 5.0.1

resources:
  - pvc.yaml
  - service.yaml
  - statefulset.yaml

patches:
  - target:
      kind: StatefulSet
    # Patch matter-server StatefulSet to use multus interface so hostNetwork: true is not needed
    patch: |-
      apiVersion: apps/v1
      kind: StatefulSet
      metadata:
        name: ignored
      spec:
        template:
          metadata:
            annotations:
              k8s.v1.cni.cncf.io/networks: '[{"name":"macvlan-conf","namespace":"kube-system"}]'
          spec:
            initContainers:
              - name: 0-init-dns-route
                image: busybox
                command:
                  - /bin/sh
                args:
                - -c
                # Add custom route so DNS can reach service CIDR
                - ip route add 10.43.0.0/16 via 10.42.0.1 dev eth0
                securityContext:
                  privileged: true
