apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ignored
spec:
  template:
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/networks: '[{"interface":"<path:vaults/homelab/items/multus-dns-route#supervisor-addons-interface>","name":"macvlan-conf","namespace":"kube-system","mac":"<matter-server>"}]'
