namespace: mosquitto

images:
  - name: eclipse-mosquitto
    newTag: 2.0.18

resources:
  - gateway.yaml
  - onepassworditem.yaml
  - pvc.yaml
  - service.yaml
  - statefulset.yaml
  - tcproute.yaml

configMapGenerator:
  - name: config
    files:
      - files/mosquitto.conf

  - name: startup
    files:
      - files/startup.sh
