apiVersion: v1
kind: ConfigMap
metadata:
  name: script
data:
  script: |+
    #!/bin/bash
    while true
    do
        new_checksum=$(md5sum /opt/static-clients/static-clients.csv)
        if [ "$new_checksum" != "$old_checksum" ]; then
            echo "Config file changed. Running script..."

            # Custom client Format
            # <Client Name>AB:CD:EF:01:23:45>0>0>>>>>
            CUSTOM_CLIENTLIST=$(awk -F ',' '{gsub(/_/, " "); print "<"$3">"toupper($1)">0>0>>>>>"}' /opt/static-clients/static-clients.csv)

            # Static Client Format
            # <AB:CD:EF:01:23:45>1.2.3.4>>Client_Name
            DHCP_STATICLIST=$(awk -F ',' '{print "<"toupper($1)">"$2">>"$3}' /opt/static-clients/static-clients.csv)

            ssh $ROUTER_USER@$ROUTER_IP \
              -p $ROUTER_SSH_PORT \
              -i /opt/ssh/id_rsa \
              -o StrictHostKeyChecking=accept-new \
              "nvram set custom_clientlist=\"$CUSTOM_CLIENTLIST\""

            ssh $ROUTER_USER@$ROUTER_IP \
              -p $ROUTER_SSH_PORT \
              -i /opt/ssh/id_rsa \
              -o StrictHostKeyChecking=accept-new \
              "nvram set dhcp_staticlist=\"$DHCP_STATICLIST\"""

            # Set checksum to current
            old_checksum=$new_checksum

            echo "Script completed."
      fi
      sleep 10
    done
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: asus-router-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: asus-router-manager
  template:
    metadata:
      labels:
        app: asus-router-manager
    spec:
      hostNetwork: true
      containers:
        - name: asus-router-manager
          image: panubo/sshd
          command:
          - /opt/script/configure.sh
          env:
            - name: ROUTER_IP
              valueFrom:
                configMapKeyRef:
                  name: ssh-config
                  key: router-ip
            - name: ROUTER_SSH_PORT
              valueFrom:
                configMapKeyRef:
                  name: ssh-config
                  key: router-ssh-port
            - name: ROUTER_USER
              valueFrom:
                configMapKeyRef:
                  name: ssh-config
                  key: router-user
          volumeMounts:
            - name: script
              mountPath: /opt/script
              readOnly: true
            - name: ssh-key
              mountPath: /opt/ssh
              readOnly: true
            - name: static-clients
              mountPath: /opt/static-clients
              readOnly: true
      volumes:
        - name: script
          configMap:
            name: script
            defaultMode: 0777
            items:
              - key: script
                path: configure.sh
        - name: ssh-key
          secret:
            secretName: ssh-key
            defaultMode: 0400
            items:
              - key: id_rsa
                path: id_rsa
        - name: static-clients
          configMap:
            name: static-clients
            items:
              - key: static-clients
                path: static-clients.csv
