apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ignored
spec:
  template:
    spec:
      initContainers:
        - name: iscsi-intaller
          image: debian:latest
          command:
            - sh
          args:
            - -c
            - apt update && apt install open-iscsi -y
          env:
            - name: DEBIAN_FRONTEND
              value: noninteractive
            - name: ROOT_MOUNT_DIR
              value: /root
          securityContext:
            privileged: true
          volumeMounts:
            - name: root-mount
              mountPath: /root
      volumes:
        - name: root-mount
          hostPath:
            path: /
