namespace: kube-system
resources:
- rbac.yaml
helmCharts:
- includeCRDs: true
  name: traefik
  namespace: kube-system
  releaseName: traefik
  repo: https://traefik.github.io/charts
  version: 25.0.0
  valuesFile: values.yaml
