namespace: kube-system
patches:
- patch: |-
    - op: replace
      path: "/apiVersion"
      value: gateway.networking.k8s.io/v1beta1
  target:
    group: gateway.networking.k8s.io
    version: v1alpha2
    kind: 'gatewayclass'
helmCharts:
- includeCRDs: true
  name: traefik
  namespace: kube-system
  releaseName: traefik
  repo: https://traefik.github.io/charts
  version: 25.0.0
  valuesFile: values.yaml
