apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
annotations:
  argocd.argoproj.io/sync-wave: "1"
helmCharts:
  - name: cert-manager
    repo: https://charts.jetstack.io
    releaseName: cert-manager
    namespace: cert-manager
