namespace: home-assistant

resources:
  - resources/ingress.yaml
  - resources/pvc.yaml
  - resources/service.yaml
  - resources/statefulset.yaml

images:
  - name: ghcr.io/home-assistant/home-assistant
    newTag: 2024.5.1
  - name: busybox
    newTag: 1.36.1

# Custom blueprints for use in home-assistant
# Updates require a yaml configuration refresh via the UI (or container restart)
configMapGenerator:
  - name: blueprints
    files:
      - files/blueprints/manual_override.yaml
      - files/blueprints/motion_activated_light.yaml
      - files/blueprints/sensor_threshold.yaml
    options:
      disableNameSuffixHash: true

  - name: blueprints-manager
    files:
      - files/blueprints-manager.sh

  - name: initial-config
    files:
      - files/configuration.yaml
    options:
      disableNameSuffixHash: true
      annotations:
        avp.kubernetes.io/path: "vaults/homelab/items/trusted-proxies"

  - name: route-manager
    files:
      - files/route-manager.sh

  - name: setup
    files:
      - files/setup.sh

patches:
  # Add custom blueprints to home-assistant
  - target:
      kind: StatefulSet
      name: home-assistant
    path: patches/blueprints-manager.yaml
  # Ensure route advertisements update the routing table
  - target:
      kind: StatefulSet
      name: home-assistant
    path: patches/route-manager.yaml
  # Enable external network interface via multus to eliminate hostNetwork: true
  - target:
      kind: StatefulSet
      name: home-assistant
    path: patches/multus-interface.yaml
  # Ensure DNS routes correctly while using multus
  # Always put this last so it becomes the first initContainer to run
  - target:
      kind: StatefulSet
      name: home-assistant
    path: ../../multus/shared/dns-route.yaml
