namespace: argocd

resources:
  - ingress.yaml
  - onepassworditem.yaml

helmCharts:
  - name: argo-cd
    namespace: argocd
    releaseName: argocd
    repo: https://argoproj.github.io/argo-helm
    valuesFile: values.yaml
    version: 5.51.6
