namespace: argocd

images:
  - name: quay.io/argoproj/argocd
    newTag: v2.9.3

helmCharts:
  - includeCRDs: true
    name: argo-cd
    namespace: argocd
    releaseName: connect
    repo: https://argoproj.github.io/argo-helm
    valuesFile: values.yaml
    version: 5.51.6

resources:
  # Add required vault secrets via OnePasswordItem CRD
  - onepassworditem.yaml

patches:
  # Enable helm within kustomize so above helmchart can be rendered
  - path: patch-configmap.yaml
    target:
      kind: ConfigMap
      name: argocd-cm
