images:
  - name: quay.io/argoproj/argocd
    newTag: v2.9.3

resources:
  # Install ArgoCD
  - https://github.com/argoproj/argo-cd//manifests/cluster-install?ref=v2.9.3
  # Enable argocd vault plugin
  - https://raw.githubusercontent.com/argoproj-labs/argocd-vault-plugin/v1.17.0/manifests/cmp-sidecar/cmp-plugin.yaml

patches:
  # Inject required sidecar for argocd vault plugin
  - https://raw.githubusercontent.com/argoproj-labs/argocd-vault-plugin/v1.17.0/manifests/cmp-sidecar/argocd-repo-server.yaml
  # Enable helm within kustomize
  - configmap.yaml
