apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: argocd-vault-plugin
  namespace: argocd
spec:
  itemPath: "vaults/homelab/items/argocd-vault-plugin"
