apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: homelab
spec:
  sourceRepos:
    - "https://github.com/beefcheeks/raspi-k3s.git"
  destinations:
    - namespace: "*"
      server: "https://kubernetes.default.svc"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
