namespace: kube-system

resources:
  - resources/middleware.yaml

helmCharts:
  - includeCRDs: true
    name: traefik
    namespace: kube-system
    releaseName: traefik
    repo: https://traefik.github.io/charts
    version: 40.3.0
    valuesFile: values.yaml
