# Reference: https://github.com/traefik/traefik-helm-chart/blob/master/traefik/values.yaml
#
# MQTTS configuration required by mosquitto
additionalArguments:
  - --entrypoints.mqtts.address=:8883/tcp
ports:
  mqtts:
    expose: true
    exposedPort: 8883
    port: 8883
    protocol: TCP

# Required for Kubernetes gateways
experimental:
  kubernetesGateway:
    enabled: true

# Increase timeout to prevent not ready state from flapping
livenessProbe:
  timeoutSeconds: 5
readinessProbe:
  timeoutSeconds: 5

# Required for Traefik to update the LoadBalancer status field
# Without this, ArgoCD apps with ingress resources get stuck in a Progressing loop
# See: https://github.com/traefik/traefik/issues/6303
providers:
  kubernetesIngress:
    publishedService:
      enabled: true

resources:
  requests:
    cpu: "100m"
    memory: "100Mi"

# Required for external IPs to be passed for allow/deny rules
service:
  spec:
    externalTrafficPolicy: Local
