experimental:
  kubernetesGateway:
    enabled: true
# Required for Traefik to update the LoadBalancer status field
# Without this, ArgoCD apps with ingress resources get stuck in a Progressing loop
# See: https://github.com/traefik/traefik/issues/6303
providers:
  kubernetesIngress:
    publishedService:
      enabled: true
service:
  spec:
    externalTrafficPolicy: Local
