# Reference: https://github.com/traefik/traefik-helm-chart/blob/master/traefik/values.yaml
#
# MQTTS configuration required by mosquitto
additionalArguments:
  - --entrypoints.mqtts.address=:8883/tcp

# Minimize possibility of 1 pod being not ready knocking out traefik LB IP
deployment:
  replicas: 2

# Don't deploy a default gateway - handled by mosquitto
gateway:
  enabled: false

# Increase timeout to prevent not ready state from flapping
livenessProbe:
  timeoutSeconds: 5
readinessProbe:
  timeoutSeconds: 5

ports:
  mqtts:
    expose:
      default: true
    exposedPort: 8883
    port: 8883
    protocol: TCP

# Required to integrate Traefik with Kubernetes GatewayClass
providers:
  kubernetesGateway:
    enabled: true
    experimentalChannel: true

resources:
  requests:
    cpu: "100m"
    memory: "100Mi"

# Required for external IPs to be passed for allow/deny rules
service:
  spec:
    externalTrafficPolicy: Local
