---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    argocd.argoproj.io/sync-options: Delete=false,Prune=false
  name: openthread-border-router
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
