kind: StatefulSet
metadata:
  name: ignored
spec:
  template:
    spec:
      containers:
        - name: adguard-home
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
