namespace: argocd

# Ensure image matches that of helm chart
images:
  - name: quay.io/argoproj/argocd
    newTag: v2.13.1

helmCharts:
  - name: argo-cd
    namespace: argocd
    releaseName: argocd
    repo: https://argoproj.github.io/argo-helm
    valuesFile: values.yaml
    version: 7.7.5
