resources:
- ../../base
- resources/onepassworditem.yaml

patches:
  # Add annotations to specify environment-specific host
  - target:
      kind: Gateway
      name: mosquitto
    path: patches/gateway.yaml
