namespace: homebridge

images:
  - name: homebridge/homebridge
    newTag: 2023-11-28

resources:
- ingress.yaml
- pvc.yaml
- service.yaml
- statefulset.yaml

# Patch Homebridge StatefulSet to use multus interface so hostNetwork: true is not needed
patches:
  # Enable macvlan interface via multus
  - target:
      kind: StatefulSet
      name: homebridge
    patch: |-
      apiVersion: apps/v1
      kind: StatefulSet
      metadata:
        name: ignored
      spec:
        template:
          metadata:
            annotations:
              k8s.v1.cni.cncf.io/networks: '[{"name":"macvlan-conf","namespace":"kube-system"}]'
