namespace: homebridge

images:
  - name: homebridge/homebridge
    newTag: 2023-11-28

resources:
- ingress.yaml
- pvc.yaml
- service.yaml
- statefulset.yaml

# Patch Homebridge StatefulSet to use multus interface so hostNetwork: true is not needed
patches:
  - target:
      kind: StatefulSet
    patch: |-
      apiVersion: apps/v1
      kind: StatefulSet
      metadata:
        name: ignored
      spec:
        template:
          metadata:
            annotations:
              k8s.v1.cni.cncf.io/networks: '[{"name":"macvlan-conf","namespace":"kube-system"}]'
          spec:
            initContainers:
              - name: 0-init-multus-dns-route
                image: busybox
                command:
                  - /bin/sh
                args:
                - -c
                # Add custom route so DNS can reach service CIDR
                - ip route add 10.43.0.0/16 via 10.42.0.1 dev eth0
                securityContext:
                  privileged: true
