apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ignored
spec:
  template:
    spec:
      containers:
        - name: logdna-agent
          env:
            - name: LOGDNA_USE_K8S_LOG_ENRICHMENT
              value: "always"
            - name: LOGDNA_LOG_K8S_EVENTS
              value: "always"
