# OnePasswordItem renders a required secret
# See: https://argocd-vault-plugin.readthedocs.io/en/stable/config/
# 1Password connect/operator: https://github.com/1Password/onepassword-operator
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: argocd-secret
spec:
  itemPath: "vaults/homelab/items/argocd-secret"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  name: argocd-vault-plugin
spec:
  itemPath: "vaults/homelab/items/argocd-vault-plugin"
