cloudflare:
  tunnelName: homelab
  secretName: cloudflare-tunnel
  ingress:
    - hostname: <path:vaults/homelab/items/ingress#home-assistant-external>
      service: https://<path:vaults/homelab/items/ingress#home-assistant-external>

image:
  tag: 2024.4.1

replicaCount: 1
