namespace: kube-system

resources:
  - resources/dhcp-daemon.yaml
  - resources/macvlan.yaml
  - https://github.com/k8snetworkplumbingwg/multus-cni/raw/v4.1.3/deployments/multus-daemonset.yml

configMapGenerator:
  - name: cni-plugins
    literals:
      - arch=arm64
      - version=v1.6.0

generatorOptions:
  annotations:
    argocd.argoproj.io/sync-wave: "-1"

# Patches required for multus and the dhcp-daemon to work on k3s
patches:
  - path: patches/cni-symlinker.yaml
    target:
      # Targets both dhcp-daemon and kube-multus-ds
      kind: DaemonSet
      namespace: kube-system
