resources:
  - cni-symlinker.yaml
  - cni-plugins.yaml
  - dhcp-daemon.yaml
  - https://raw.githubusercontent.com/k8snetworkplumbingwg/multus-cni/v4.0.2/deployments/multus-daemonset.yml
  - macvlan.yaml
