resources:
  - cni-plugins.yaml
  - dhcp-daemon.yaml
  - https://raw.githubusercontent.com/k8snetworkplumbingwg/multus-cni/v4.0.2/deployments/multus-daemonset.yml
  - macvlan.yaml

# Patches required for multus and the dhcp-daemon to work on k3s
patches:
  - path: patch.yaml
    target:
      # Targets both dhcp-daemon and kube-multus-ds
      kind: DaemonSet
      namespace: kube-system
