apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: macvlan-conf
  namespace: kube-system
spec:
  config: |
    {
      "cniVersion": "1.3.0",
      "type": "macvlan",
      "master": "eth0",
      "capabilities": {"mac": true},
      "ipam": {
        "type": "dhcp"
      }
    }
