default_config:

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - <localhost>
    - <k3s-pods>

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
template: !include template.yaml
