# This file is the root application for the applicationset
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: root
  namespace: argocd
spec:
  project: homelab
  source:
    repoURL: https://github.com/beefcheeks/raspi-k3s
    targetRevision: stage
    path: argocd/appsets
  destination:
    name: in-cluster
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
