namespace: logdna-agent

resources:
  - resources/onepassworditem.yaml
  # Syslog to https log forwarder
  - https://github.com/logdna/logdna-rsyslog/raw/c17ce1bf9a7160c74f4820518f01229882742aae/logdna-rsyslog-config-https.yml
  - https://github.com/logdna/logdna-rsyslog/raw/c17ce1bf9a7160c74f4820518f01229882742aae/logdna-rsyslog-workload.yml
  # Actual agent
  - https://github.com/logdna/logdna-agent-v2/raw/3.9.1/k8s/agent-resources.yaml

patches:
  # Patch to make rsyslog service type LoadBalancer for router logs
  - target:
       kind: Service
    patch: |-
      apiVersion: v1
      kind: Service
      metadata:
        name: logdna-rsyslog-tcp
        namespace: logdna-agent
      spec:
        type: LoadBalancer
  # Patch to enable Kubernetes metrics and events
  - target:
       kind: DaemonSet
       namespace: logdna-agent
    patch: |-
      apiVersion: apps/v1
      kind: DaemonSet
      metadata:
        name: ignored
      spec:
        template:
           spec:
              containers:
                - name: logdna-agent
                  env:
                    - name: LOGDNA_USE_K8S_LOG_ENRICHMENT
                      value: "always"
                    - name: LOGDNA_LOG_K8S_EVENTS
                      value: "always"
