apiVersion: v1
kind: ConfigMap
metadata:
  name: ignored
  annotations:
    avp.kubernetes.io/path: "vaults/homelab/items/ips"
data:
  configuration: |+
    default_config:

    http:
      use_x_forwarded_for: true
      trusted_proxies:
        - 127.0.0.0
        - <k8s-cidr>

    automation: !include automations.yaml
    script: !include scripts.yaml
    scene: !include scenes.yaml
    template: !include template.yaml
