resources:
- ../../base

patches:
  # Add annotations to specify env-specific multus mac address
  - target:
      kind: StatefulSet
      name: home-assistant
    path: patches/multus-interface.yaml
