# Used for mocking centralized supervisor api
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mock-supervisor
  name: mock-supervisor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mock-supervisor
  template:
    metadata:
      labels:
        app: mock-supervisor
    spec:
      containers:
      - name: mock-supervisor
        image: nginx:latest
        volumeMounts:
          - name: nginx-config
            mountPath: /etc/nginx/conf.d
      volumes:
      - name: nginx-config
        configMap:
          name: mock-supervisor
