{{- if .Values.feature.externalIngress }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name  }}-external
  labels:
    {{- include "homebridge.labels" . | nindent 4 }}
  {{- with .Values.externalIngress.annotations }}
  annotations:
    {{- toYaml . | nindent 8 }}
  {{- end }}
spec:
  tls:
    - hosts:
      - {{ .Values.externalIngress.host }}
      secretName: {{ .Values.externalIngress.tls.secretName }}
  rules:
    - host: {{ .Values.externalIngress.host | quote }}
      http:
        paths:
        {{- if .Values.externalIngress.path.webhook }}
        - path: {{ .Values.externalIngress.path.webhook }}
          pathType: Prefix
          backend:
            service:
              name: {{ .Chart.Name  }}
              port:
                number: {{ .Values.service.port.webhook }}
        {{- end }}
        {{- if .Values.externalIngress.path.ui }}
        - path: {{ .Values.externalIngress.path.ui }}
          pathType: Prefix
          backend:
            service:
              name: {{ .Chart.Name  }}
              port:
                number: {{ .Values.service.port.ui }}
        {{- end }}
{{- end }}
