apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Chart.Name  }}
spec:
  {{- if .Values.pvc.storageClassName }}
  storageClassName: {{ .Values.pvc.storageClassName }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.pvc.storage }}
  accessModes:
    - ReadWriteOnce
