apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Chart.Name  }}
  labels:
    {{- include "homebridge.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "homebridge.selectorLabels" . | nindent 6 }}
  serviceName: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        {{- include "homebridge.selectorLabels" . | nindent 8 }}
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name:  {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        {{- if .Values.statefulset.timezone }}
        - name: tz
          value: {{ .Values.statefulset.timezone }}
        {{- end }}
        {{- if .Values.statefulset.port.ui }}
        - name: HOMEBRIDGE_CONFIG_UI_PORT
          value: "{{ .Values.statefulset.port.ui }}"
        {{- end }}
        volumeMounts:
        - name: {{ .Chart.Name  }}
          mountPath: /homebridge
          readOnly: false
        {{- if .Values.feature.bluetooth }}
        - name: bluetooth
          mountPath: /etc/services.d/bluetoothd
          readOnly: true
        - name: dbus
          mountPath: /var/run/dbus
        - name: startup
          mountPath: /defaults/startup.sh
          subPath: startup.sh
          readOnly: true
        {{- end }}
        securityContext:
          privileged: true
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
      volumes:
      - name: {{ .Chart.Name  }}
        persistentVolumeClaim:
          claimName: homebridge
      {{- if .Values.feature.bluetooth }}
      - name: bluetooth
        configMap:
          name: {{ .Chart.Name  }}
          items:
          - key: bluetooth
            path: run
            mode: 0111
      - name: dbus
        hostPath:
          path: /var/run/dbus
      - name: startup
        configMap:
          name: homebridge
          items:
          - key: startup
            path: startup.sh
            mode: 0444
      {{- end }}
