apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: homelab
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators:
          - git:
              repoURL: https://github.com/beefcheeks/raspi-k3s.git
              revision: HEAD
              files:
                - path: argocd/envs/homelab/config/apps.yaml
          - list:
              elements: []
              elementsYaml: "{{ .apps | toJson }}"
  template:
    metadata:
      name: "{{ .app }}"
    spec:
      project: homelab
      source:
        repoURL: https://github.com/beefcheeks/raspi-k3s.git
        targetRevision: HEAD
        path: "argocd/apps/{{ .app }}/homelab"
      destination:
        name: in-cluster
      syncPolicy:
        automated:
          prune: true
