apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: raspi-k3s
spec:
  generators:
    - list:
        elements:
          - app: argocd
          - app: cert-manager
          - app: gateway
          - app: multus
  template:
    metadata:
      name: "{{ .app }}"
    spec:
      source:
        repoURL: https://github.com/beefcheeks/raspi-k3s.git
        targetRevision: HEAD
        path: "argocd/apps/{{ .app }}/overlays/homelab"
      destination:
        server: https://kubernetes.default.svc
      syncPolicy:
        automated:
          prune: true
