apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: homelab
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators:
          - list:
              elements:
                - app: argocd
                - app: cert-manager
          - list:
              elements:
                - cluster: in-cluster
  template:
    metadata:
      name: "{{ .app }}"
    spec:
      project: homelab
      source:
        repoURL: https://github.com/beefcheeks/raspi-k3s
        targetRevision: main
        path: "argocd/apps/{{ .app }}/overlays/homelab"
      destination:
        name: "{{ .cluster }}"
      syncPolicy:
        automated:
          prune: true
