apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: homelab
spec:
  goTemplate: true
  generators:
    - matrix:
        generators:
          - git:
              repoURL: https://github.com/beefcheeks/raspi-k3s.git
              revision: stage
              files:
                - path: argocd/config/stage.yaml
          - list:
              elements: []
              elementsYaml: '{{ .apps | toJson }}'
  # Requires progressive sync to be enabled in argocd
  strategy:
    type: RollingSync
    rollingSync:
      steps:
        - matchExpressions:
            - key: wave
              operator: In
              values:
                - '0'
        - matchExpressions:
            - key: wave
              operator: In
              values:
                - '1'
        - matchExpressions:
            - key: wave
              operator: In
              values:
                - '2'
        - matchExpressions:
            - key: wave
              operator: In
              values:
                - '3'
        - matchExpressions:
            - key: wave
              operator: In
              values:
                - '4'
  template:
    metadata:
      name: '{{ .app }}'
      labels:
        wave: '{{ .wave }}'
    spec:
      project: homelab
      source:
        repoURL: https://github.com/beefcheeks/raspi-k3s.git
        targetRevision: stage
        path: 'argocd/apps/{{ .app }}/{{ .path | default "overlays/stage" }}'
      destination:
        name: in-cluster
        namespace: '{{ .namespace }}'
  templatePatch: |
    spec:
      {{- if or (.autoSync | default true) (if .syncOptions | default [-"CreateNamespace=true"]) }}
      syncPolicy:
        automated:
          prune: {{ .prune | default true }}
          selfHeal: {{ .selfHeal | default true }}
        syncOptions: .syncOptions
      {{- end }}
