apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
annotations:
  argocd.argoproj.io/sync-wave: "0"
resources:
  - https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.0.0/standard-install.yaml
