apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ignored
spec:
  template:
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/networks: '[{"name":"macvlan-conf","namespace":"kube-system","mac":"<home-assistant>"}]'
