apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: homelab
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators:
          - git:
              repoURL: https://github.com/beefcheeks/raspi-k3s.git
              revision: HEAD
              files:
                - path: argocd/config.yaml
          - list:
              elements: []
              elementsYaml: "{{ .apps | toJson }}"
  # Requires progressive sync to be enabled in argocd
  strategy:
    type: RollingSync
    rollingSync:
      steps:
        - matchExpressions:
            - key: wave
              operator: In
              values:
                - "0"
        - matchExpressions:
            - key: wave
              operator: In
              values:
                - "1"
        - matchExpressions:
            - key: wave
              operator: In
              values:
                - "2"
        - matchExpressions:
            - key: wave
              operator: In
              values:
                - "3"
  template:
    metadata:
      name: "{{ .app }}"
      labels:
        wave: "{{ .wave }}"
    spec:
      project: homelab
      source:
        repoURL: https://github.com/beefcheeks/raspi-k3s.git
        targetRevision: HEAD
        path: "argocd/apps/{{ .app }}"
      destination:
        name: in-cluster
        namespace: "{{ .namespace }}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 1
            maxDuration: 1m
        syncOptions:
          - CreateNamespace=true
