apps:
  # Wave 0
  - app: gateway
    namespace: kube-system
    wave: "0"
  - app: multus
    namespace: kube-system
    wave: "0"
  - app: onepassword
    namespace: onepassword
    wave: "0"
  # Wave 1
  - app: cert-manager
    namespace: cert-manager
    wave: "1"
  - app: logdna-agent
    namespace: logdna-agent
    wave: "1"
  - app: traefik
    namespace: kube-system
    wave: "1"
  # Wave 2
  - app: argocd
    namespace: argocd
    wave: "2"
  # Wave 3
  - app: argocd-ingress
    namespace: argocd
    wave: "3"
  - app: home-assistant
    namespace: home-assistant
    wave: "3"
  - app: homebridge
    namespace: homebridge
    wave: "3"
  - app: matter-server
    namespace: home-assistant
    wave: "3"
  - app: mosquitto
    namespace: mosquitto
    wave: "3"
