helmCharts:
  - name: cert-manager
    repo: https://charts.jetstack.io
    releaseName: cert-manager
    namespace: cert-manager
    version: v1.13.2
    valuesInLine:
      installCRDs: true
      extraArgs:
        - --feature-gates=ExperimentalGatewayAPISupport=true
