namespace: cert-manager
resources:
  - namespace.yaml
helmCharts:
  - name: cert-manager
    repo: https://charts.jetstack.io
    namespace: cert-manager
    version: v1.13.2
    valuesFile: values.yaml
