# Create shared middlewares for use in ingresses across multiple namespaces
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: ip-allow-list
  namespace: kube-system
spec:
  ipWhiteList:
    sourceRange:
      - 127.0.0.1/32
      - 10.0.0.0/24
      - 10.6.0.0/28
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: https-redirect
  namespace: kube-system
spec:
  redirectScheme:
    permanent: true
    scheme: https
