# Adapted from: https://github.com/k8snetworkplumbingwg/reference-deployment/blob/master/multus-dhcp/dhcp-daemonset.yml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: dhcp-daemon
  name: dhcp-daemon
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: dhcp-daemon
  template:
    metadata:
      labels:
        app: dhcp-daemon
    spec:
      # Required to actually request IP from host network gateway
      hostNetwork: true 
      initContainers:
      - name: install-cni-plugins
        image: busybox
        env:
        # ARCH and VERSION taken from: https://github.com/containernetworking/plugins/releases
        - name: ARCH
          valueFrom: 
            configMapKeyRef:
              name: cni-plugins
              key: arch
        - name: VERSION
          valueFrom:
            configMapKeyRef:
              name: cni-plugins
              key: version
        command:
        - /bin/sh
        args:
        - -c
        - wget -O- https://github.com/containernetworking/plugins/releases/download/$(VERSION)/cni-plugins-linux-$(ARCH)-$(VERSION).tgz | tar xz --strip-components=1 -C /host/opt/cni/bin/
        securityContext:
          privileged: true
        volumeMounts:
        - name: bin
          mountPath: /host/opt/cni/bin
      - name: clean-up-socket
        image: busybox
        command:
        - /bin/sh
        args:
        - -c
        - rm -f /host/run/cni/dhcp.sock
        securityContext:
          privileged: true
        volumeMounts:
        - name: socket
          mountPath: /host/run/cni
      containers:
      - image: busybox
        imagePullPolicy: Always
        name: dhcp-daemon
        command:
        - /host/opt/cni/bin/dhcp
        args:
        - daemon
        - -hostprefix
        - /host
        resources:
          requests:
            cpu: "100m"
            memory: "50Mi"
          limits:
            cpu: "100m"
            memory: "50Mi"
        securityContext:
          privileged: true
        volumeMounts:
        - name: bin
          mountPath: /host/opt/cni/bin/
          readOnly: true
        - name: netns
          mountPath: /host/var/run/netns
          # Removal of mountPropagation property causes 'unknown fs magic' error
          mountPropagation: HostToContainer
        - name: proc
          mountPath: /host/proc
        - name: socket
          mountPath: /host/run/cni
      restartPolicy: Always
      volumes:
      - name: bin
        hostPath:
          path: /opt/cni/bin
      - name: netns
        hostPath:
          path: /var/run/netns
      - name: proc
        hostPath:
          path: /proc
      - name: socket
        hostPath:
          path: /run/cni
