apiVersion: v1
kind: ConfigMap
metadata:
  name: homebridge
data:
  bluetooth: |+
    #!/bin/bash
    echo "Starting bluetooth daemon"
    exec bluetoothd -d
  startup: |+
    #!/bin/bash
    apt-get update
    apt-get install -y bluetooth bluez libbluetooth-dev libudev-dev
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: homebridge
  labels:
    app: homebridge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homebridge
  serviceName: homebridge
  template:
    metadata:
      labels:
        app: homebridge
      name: homebridge
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: homebridge
        image: oznu/homebridge:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8581
          name: http
        - containerPort: 51828
          name: webhook
        env:
        - name: tz
          value: 'America/Los_Angeles'
        volumeMounts:
        - name: homebridge
          mountPath: /homebridge
          readOnly: false
        # Comment out the 3 lines directly below this if you don't need Bluetooth
        - name: bluetooth
          mountPath: /etc/services.d/bluetoothd
          readOnly: true
        - name: startup
          mountPath: /defaults/startup.sh
          subPath: startup.sh
          readOnly: true
        securityContext:
          privileged: true
          procMount: Default
      volumes:
      - name: homebridge
        persistentVolumeClaim:
          claimName: homebridge
      - name: bluetooth
        configMap:
          name: homebridge
          items:
          - key: bluetooth
            path: run
            mode: 0111
      - name: startup
        configMap:
          name: homebridge
          items:
          - key: startup
            path: startup.sh
            mode: 0444
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homebridge
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi
