# Default values for homebridge.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  repository: oznu/homebridge
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

nameOverride: ""
fullnameOverride: ""

feature:
  bluetooth: true
  ingress: true
  externalIngress: true

deployment:
  timezone: America/Los_Angeles
  port:
    ui: 8581
    webhook: 51828

pvc:
  storage: 1Gi
  storageClassName: local-path

service:
  type: ClusterIP
  port:
    ui: 80
    webhook: 8080

ingress:
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: letsencrypt-prod
  host: my.domain.com
  path:
    ui: /
    webhook: /webhook
  tls:
    secretName: homebridge

externalIngress:
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: letsencrypt-prod
    ingress.kubernetes.io/auth-type: basic
    ingress.kubernetes.io/auth-secret: ingress-basic-auth
  host: other.domain.com
  path:
    webhook: /hb
  tls:
    secretName: webhooks

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi
