# By default, k3s uses separate CIDRs for pods and services
# multus only detects the pod CIDR and not the service CIDR
# As a result, k8s service requests are routed via the external interface
# This includes kube-dns, which can only be routed through the pod interface
# This patch is intended for other apps' StatefulSets that use the multus interface
kind: StatefulSet
metadata:
  name: ignored
spec:
  template:
    spec:
      initContainers:
        - name: 0-init-dns-route
          image: busybox:1.36.1
          command:
            - /bin/sh
          args:
          - -c
          # Add custom route so DNS can reach service CIDR
          - ip route add $SERVICE_CIDR via $GATEWAY dev $INTERFACE
          env:
          - name: SERVICE_CIDR
            value: <path:vaults/homelab/items/multus-dns-route#service-cidr>
          - name: GATEWAY
            value: <path:vaults/homelab/items/multus-dns-route#gateway>
          - name: INTERFACE
            value: <path:vaults/homelab/items/multus-dns-route#interface>
          securityContext:
            privileged: true
