# Intended for k3s only
# k3s uses non-standard cni configuration paths
# Symlinking them to the standard ones ensures multus works correctly
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ignored
spec:
  template:
    spec:
      initContainers:
        - name: configure-cni
          image: busybox
          command:
            - /bin/sh
          args:
            - -c
            - |
              # Symlink cni binaries and config to default locations
              if [ ! -L /host/etc/cni/net.d ]; then
                  ln -s /var/lib/rancher/k3s/agent/etc/cni/net.d /host/etc/cni/net.d
              fi
              if [ ! -L /host/opt/cni/bin ]; then
                  ln -s /var/lib/rancher/k3s/data/current/bin /host/opt/cni/bin
              fi
              # Remove multus conf file to prevent nested config bug
              # See: https://github.com/k8snetworkplumbingwg/multus-cni/issues/1089#issuecomment-1550442393
              if [ -f /host/etc/cni/net.d/00-multus.conflist ]; then
                  rm /host/etc/cni/net.d/00-multus.conflist
              fi
          securityContext:
            privileged: true
          volumeMounts:
            - name: etc
              mountPath: /host/etc/cni
            - name: flannel
              mountPath: /host/var/lib/rancher/k3s/agent/etc/flannel
            - name: opt
              mountPath: /host/opt/cni
      volumes:
        - name: etc
          hostPath:
            path: /etc/cni
        - name: flannel
          hostPath:
            path: /var/lib/rancher/k3s/agent/etc/flannel
        - name: opt
          hostPath:
            path: /opt/cni
