kind: DaemonSet
metadata:
  name: dhcp-daemon
  namespace: kube-system
spec:
  template:
    spec:
      volumes:
        - name: bin
          hostPath:
            path: /var/lib/rancher/k3s/data/current/bin
