kind: DaemonSet
metadata:
  name: kube-multus-ds
  namespace: kube-system
spec:
  template:
    spec:
      volumes:
        - name: cni
          hostPath:
            path: /var/lib/rancher/k3s/agent/etc/cni/
        - name: cnibin
          hostPath:
            path: /var/lib/rancher/k3s/data/current/bin
