apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: matter-server
  name: matter-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: matter-server
  template:
    metadata:
      labels:
        app: matter-server
    spec:
      # Used to mock supervisor api
      hostAliases:
        - ip: "127.0.0.1"
          hostnames:
            - "supervisor"
      containers:
      - name: matter-supervisor
        image: nginx:latest
        volumeMounts:
          - name: nginx-config
            mountPath: /etc/nginx/conf.d
      - image: homeassistant/aarch64-addon-matter-server:latest
        imagePullPolicy: Always
        name: matter-server
        ports:
        - containerPort: 5580
        # Only needed for bluetooth access
        # securityContext:
        #   privileged: true
        resources:
          requests:
            memory: 100Mi
            cpu: 100m
          limits:
            memory: 500Mi
            cpu: 500m
        volumeMounts:
        - name: data
          mountPath: /data
        # Only needed for bluetooth access
        # - name: dbus
        #   mountPath: /run/dbus
        #   readOnly: True
      restartPolicy: Always
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: matter-server
      - name: nginx-config
        configMap:
          name: matter-supervisor
      # Only needed for bluetooth access
      # - name: dbus
      #   hostPath:
      #     path: /run/dbus
