apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  annotations:
    operator.1password.io/auto-restart: "true"
  name: ssh-config
spec:
  itemPath: "vaults/homelab/items/router-ssh-config"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  annotations:
    operator.1password.io/auto-restart: "true"
  name: ssh-key
spec:
  itemPath: "vaults/homelab/items/router-ssh-key"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  annotations:
    operator.1password.io/auto-restart: "true"
  name: static-clients
spec:
  itemPath: "vaults/homelab/items/static-clients"
