apiVersion: v2
type: application
name: cert-manager
annotations:
  argocd.argoproj.io/sync-wave: "0"
version: 1.0.0
appVersion: "1.0.0"
dependencies:
  - name: cert-manager
    version: v1.13.2
    repository: https://charts.jetstack.io
