namespace: cert-manager

resources:
  - resources/clusterissuer.yaml
  - resources/onepassworditem.yaml

helmCharts:
  - name: cert-manager
    namespace: cert-manager
    releaseName: cert-manager
    repo: https://charts.jetstack.io
    version: v1.13.2
    valuesFile: values.yaml
