namespace: cert-manager
resources:
  - clusterissuer.yaml
  - namespace.yaml
  - onepasworditem.yaml
helmCharts:
  - name: cert-manager
    namespace: cert-manager
    releaseName: cert-manager
    repo: https://charts.jetstack.io
    version: v1.13.2
    valuesFile: values.yaml
