apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: cloudflare
  namespace: cert-manager
spec:
  api-token: "vaults/homelab/items/cloudflare-cert-manager"
