---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cloudflare-ddns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflare-ddns
  template:
    metadata:
      labels:
        app: cloudflare-ddns
    spec:
      containers:
      - name: cloudflare-ddns
        image: favonia/cloudflare-ddns:latest
        imagePullPolicy: Always
        env:
        - name: CLOUDFLARE_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: cloudflare-ddns
              key: api-token
        - name: DOMAINS
          value: <ddns-external>
        - name: PUID
          value: '1000'
        - name: PGID
          value: '1000'
