namespace: home-assistant

resources:
- ingress.yaml
- pvc.yaml
- service.yaml
- statefulset.yaml

images:
  - name: ghcr.io/home-assistant/home-assistant
    newTag: "2023.12.3"

# Custom blueprints for use in home-assistant
# Updates require a yaml configuration refresh via the UI (or container restart)
configMapGenerator:
  - name: blueprints
    files:
      - files/blueprints/automation-manual-override.yaml
      - files/blueprints/motion-activated-light.yaml
      - files/blueprints/sensor-threshold-activated-light.yaml

  - name: initial-config
    files:
      - files/initial-config.yaml

  - name: route-manager
    files:
      - files/route-manager.sh

  - name: setup
    files:
      - files/setup.sh

patches:
  # Add configuration to support ingress
  - target:
      kind: ConfigMap
      name: initial-config
    path: patches/initial-config.yaml
  # Add custom blueprints to home-assistant
  - target:
      kind: StatefulSet
      name: home-assistant
    path: patches/blueprints.yaml
  # Ensure route advertisements update the routing table
  - target:
      kind: StatefulSet
      name: home-assistant
    path: patches/route-manager.yaml
  # Enable external network interface via multus to eliminate hostNetwork: true
  - target:
      kind: StatefulSet
      name: home-assistant
    patch: |-
      apiVersion: apps/v1
      kind: StatefulSet
      metadata:
        name: ignored
      spec:
        template:
          metadata:
            annotations:
              k8s.v1.cni.cncf.io/networks: '[{"name":"macvlan-conf","namespace":"kube-system"}]'
  # Ensure DNS routes correctly while using multus
  # Always put this last so it becomes the first initContainer to run
  - target:
      kind: StatefulSet
      name: home-assistant
    path: ../multus/patches/dns-route.yaml
