namespace: home-assistant

resources:
- blueprints.yaml # Only needed if using custom blueprints
- configmap.yaml
- ingress.yaml
- pvc.yaml
- route-manager.yaml # Only needed if using route advertisement
- service.yaml
- statefulset.yaml

images:
  - name: ghcr.io/home-assistant/home-assistant
    newTag: "2023.12.3"

patches:
  # Patch default configuration for initial setup
  - target:
      kind: ConfigMap
      name: home-assistant
    patch: |-
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: ignored
      data:
        configuration: |+
          default_config:

          http:
            use_x_forwarded_for: true
            trusted_proxies:
              - 127.0.0.0
              - 10.42.0.0/24

          automation: !include automations.yaml
          script: !include scripts.yaml
          scene: !include scenes.yaml
          template: !include template.yaml

  - target:
      kind: StatefulSet
      name: home-assistant
    patch: |-
      # Patch home-assistant StatefulSet to mount custom blueprint directory for init script
      apiVersion: apps/v1
      kind: StatefulSet
      metadata:
        name: ignored
      spec:
        template:
          spec:
            initContainers:
            - name: init-home-assistant
              volumeMounts:
                - name: blueprints
                  mountPath: /opt/blueprints
            containers:
            - name: home-assistant
              volumeMounts:
                - name: blueprints
                  mountPath: /opt/blueprints
            volumes:
              - name: blueprints
                configMap:
                  name: blueprints
  - target:
      kind: StatefulSet
      name: home-assistant
    patch: |-
      # Patch home-assistant StatefulSet to use multus interface so hostNetwork: true is not needed
      apiVersion: apps/v1
      kind: StatefulSet
      metadata:
        name: ignored
      spec:
        template:
          metadata:
            annotations:
              k8s.v1.cni.cncf.io/networks: '[{"name":"macvlan-conf","namespace":"kube-system"}]'
  - target:
      kind: StatefulSet
      name: home-assistant
    patch: |-
      # Patch home-assistant StatefulSet to use route manager needed for thread border route advertisement
      apiVersion: apps/v1
      kind: StatefulSet
      metadata:
        name: ignored
      spec:
        template:
          spec:
            # Ensure route advertisement works
            containers:
              - name: route-manager
                image: apearson/radvd:latest
                command:
                - /opt/scripts/route-manager.sh
                securityContext:
                  privileged: true
                volumeMounts:
                - name: route-manager
                  mountPath: /opt/scripts
            volumes:
              - name: route-manager
                configMap:
                  name: route-manager
                  defaultMode: 0777
                  items:
                    - key: route-manager
                      path: route-manager.sh
